#!/usr/bin/env bash

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
REPO_PATH=`(realpath $SCRIPT_PATH/..)`

CMAKE_BUILD_TYPE="Release"
VCPKG_MANIFEST_FEATURES="core"
ENABLE_SANDBOX="OFF"
ENABLE_TEST="OFF"
GENERATOR="Ninja"
TRIPLET=""

HELP()
{
    echo "[-h|d|t|s]"
    echo "options:"
    echo "h         Print this help"
    echo "d         Configure Debug Build (default: Release)"
    echo "t         Enable Tests"
    echo "s         Enable Sandboxes"
    echo "n         Use libc++ (triplet)"
}

while getopts ":hdtsn" option; do
    case $option in
        h)
            HELP
            exit 0;;
        d)
            CMAKE_BUILD_TYPE="Debug";;
        t)
            TEST="test"
            VCPKG_MANIFEST_FEATURES="${TEST};${VCPKG_MANIFEST_FEATURES}"
            ENABLE_TEST="ON";;
        s)
            SANDBOX="sandbox"
            VCPKG_MANIFEST_FEATURES="${SANDBOX};${VCPKG_MANIFEST_FEATURES}"
            ENABLE_SANDBOX="ON";;
        n)
            TRIPLET="-DVCPKG_TARGET_TRIPLET=nil-libcxx -DVCPKG_HOST_TRIPLET=nil-libcxx";;
        \?)
            echo "unknown option is provided: ${option}"
            HELP
            exit 1;;
    esac
done

export VCPKG_BINARY_SOURCES="default"
export CMAKE_BUILD_PARALLEL_LEVEL=8

cmake                                                                       \
    -B${REPO_PATH}/.build                                                   \
    -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake   \
    -DCMAKE_INSTALL_PREFIX=${REPO_PATH}/.build/out                          \
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}                                  \
    -G${GENERATOR}                                                          \
    -DVCPKG_MANIFEST_FEATURES=${VCPKG_MANIFEST_FEATURES}                    \
    -DVCPKG_OVERLAY_TRIPLETS=${REPO_PATH}/triplets                          \
    -DENABLE_SANDBOX=${ENABLE_SANDBOX}                                      \
    -DENABLE_TEST=${ENABLE_TEST}                                            \
    ${TRIPLET}
