#!/usr/bin/env bash

if [[ $0 != $BASH_SOURCE ]]; then
    echo "do not source this script"
    return 1
fi

export CC=`(which gcc-11)`
export CXX=`(which g++-11)`

SCRIPT_PATH=`(dirname $BASH_SOURCE)`
BUILD_PATH=`(realpath $SCRIPT_PATH/../.build)`
mkdir -p $BUILD_PATH
cd $BUILD_PATH
cmake ..                    \
    --preset ${1:-debug}